### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by mentalstring**
Fix build badge and update supported PHP version.

### CODE REVIEW

**Review by connorhu — APPROVED** [review]

**Comment by connorhu** [comment]
Thank you the update! If you have time, you could also update the symfony version. Instead of a specific version, some general text would be fine.

**Comment by mentalstring** [comment]
Done and also updated some links.

@thePanz Could you maybe replace the _PHP 7 support_ with support up to PHP 8.3 on the repo `About`, and update the repo link to https://symfony.com/legacy?

**Review by thirsch — APPROVED** [review]
Thanks!

**Comment by thePanz** [comment]
Thanks @mentalstring , merged!

**Pull request merged**
