### PR TITLE
Fixed a few more php 8 issues

### PR DESCRIPTION
**Pull request by thirsch**
Using the current release, we have found the following issues under php 8.1

### CODE REVIEW

**Comment by thirsch** [comment]
The testsuite is currently not working under Apple M1. I'll get myself a amd64 test machine and come back with fix.

**Comment by thirsch** [comment]
> The testsuite is currently not working under Apple M1. I'll get myself a amd64 test machine and come back with a fix.

Tests are running fine on my local machine and over in the fork of the repository. Any idea, why it crashed here? Can you re-run them manually or do I have to push a change to the branch to start them again?

**Review by thePanz — APPROVED** [review]
@thirsch : re-run the failing job, it's green now
Could you please rebase this PR?

**Comment by thirsch** [comment]
> @thirsch : re-run the failing job, it's green now Could you please rebase this PR?

done

**Comment by mkopinsky** [comment]
@thirsch were you able to get tests to run on Mac M1?

**Pull request merged**
