### PR TITLE
Rename package to `friendsofsymfony1/symfony1`

### LINKED ISSUE #203: Fix supported PHP version on composer requirements
In order to expose what PHP version the library support we need to update composer requirements with the right one.

Regarding tests environment execution the minimum version is currently PHP 5.3.0.

### PR DESCRIPTION
**Pull request by j0k3r**
- Add PHP requirements
- Cleanup Travis
- Update changelog

Fix #203 & #226

### CODE REVIEW

**Comment by spirit-q2** [comment]
@j0k3r can we expect 1.5.13 soon? ;)

**Comment by j0k3r** [comment]
Really soon

**Comment by spirit-q2** [comment]
does anyone know how long it takes to make package accessible via `friendsofsymfony1/symfony1` in composer?

**Comment by j0k3r** [comment]
I don't know I tried to manually update the package may times but nothing changed..
Just monitor https://packagist.org/packages/friendsofsymfony1/ 🤷‍♂️

**Comment by alquerci** [comment]
@j0k3r See https://github.com/FriendsOfSymfony1/doctrine1/pull/63#pullrequestreview-171897254

So I guess it miss some steps.

**Comment by j0k3r** [comment]
I got a warning:
> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at friendsofsymfony1

@thePanz could you give me access to the namespace `friendsofsymfony1` on packagist?

**Comment by thePanz** [comment]
@j0k3r there is no `friendsofsymfony1/symfony1` package, and no possibility to give you access to the "organization".
I guess the error is coming from the fact that `https://packagist.org/packages/lexpress/symfony1` vendor is using the same git-repository (https://github.com/FriendsOfSymfony1/symfony1)?

**Comment by alquerci** [comment]
@thePanz look at https://github.com/FriendsOfSymfony1/doctrine1/pull/63#pullrequestreview-171897254

Your concern is not an issue as Packagist handle that, only reference to commit with the new name are modified.

**Comment by thePanz** [comment]
@alquerci @j0k3r : the new package is now live, and I set the `lexpress/symfony1` as abandoned! :)

**Pull request merged**
