### PR TITLE
update the SYMFONY_VERSION constant to the latest release number

### PR DESCRIPTION
**Pull request by verfriemelt-dot-org**
hi,

just a minor fix in context with #354 

cheers :v:

### CODE REVIEW

**Review by connorhu — APPROVED** [review]

**Comment by thePanz** [comment]
@connorhu @verfriemelt-dot-org  it should be 1.5.20-dev, as 1.5.19 has been tagged few days ago :)

**Comment by connorhu** [comment]
@thePanz Are we here already? Time flies (and version numbers)

**Comment by verfriemelt-dot-org** [comment]
i updated it to 1.5.20 :) i think this was at some time done automatically via https://github.com/FriendsOfSymfony1/symfony1/blob/master/data/bin/release.php#L85
maybe a simple version file would be a simple solution.

something like this in the release pipeline:

```sh
$ git describe --tags > version
```

and just reading in that file from the lib-root instead of replacing that token in the php file.
with that we could just leave the version at `main` or `1.5.x-dev` :thinking:

**Comment by thePanz** [comment]
> [...]with that we could just leave the version at `main` or `1.5.x-dev` 🤔

Having '1.5.x-dev' would be nice, we might also want to rename the 'main' branch to be '1.5.x' too, to simplify the management of -dev aliases (loke we have I for swiftmailer)

Wdyt?

**Review by thePanz — APPROVED** [review]

**Pull request merged**
