### PR TITLE
Remove notice appeared on php 7.4

### PR DESCRIPTION
**Pull request by spirit-q2**
PHP Notice: Trying to access array offset on value of type null in sfForm.class.php on line 947`

### CODE REVIEW

**Comment by alquerci** [comment]
Duplicates #227.

**Comment by spirit-q2** [comment]
> Duplicates #227.

Only by name. My PR is fixing root issue (algorithm error in the code), while mentioned PR fixes only a symptom (i.e. removes a warning) ;)

**Comment by alquerci** [comment]
The merger will took the decision, as the same decision was recommended on code review.

cc @valepu

**Comment by valepu** [comment]
Yes I agreed in the discussion this is the best way. I should've probably just closed my pull request

**Comment by j0k3r** [comment]
Same as #228, why does that notice never popup on Travis?

**Comment by alquerci** [comment]
@j0k3r see https://github.com/FriendsOfSymfony1/symfony1/pull/227#issuecomment-614046594

In short the error reporting configuration.

**Comment by j0k3r** [comment]
@alquerci but I can't find where that level is defined. Do you?

**Comment by alquerci** [comment]
@j0k3r me too, searched but not found.

So need an investigation.

**Comment by j0k3r** [comment]
Can't find it and don't have time to work on it.

**Comment by alquerci** [comment]
@j0k3r me too, no time.

**Pull request merged**
