### PR TITLE
PHP8

### PR DESCRIPTION
**Pull request by teymour**
PHP8 corrections

### CODE REVIEW

**Comment by alquerci** [comment]
Hello @teymour 

That's a huge work here.

Can you base your work on #262 and #263 ?

**Review by Tybaze — COMMENTED** [review]
Please be carefull,

date and strftime do not share the same format.

You can change the default timeFormat, but it will break a lot of setup (because default Sf1 timeformat is missing year, it's common to change it)

I'll try to provide a fix

**Comment by Tybaze** [comment]
I think we can close this PR, everything has been included into the merged #266 

Thank you very much @teymour your list of modifications was usefull 👍

**Comment by teymour** [comment]
> Thank you very much @teymour your list of modifications was usefull +1

Thanks for your work ! This new version works on our projects on PHP 8.1 and 7.4. It's a great news !!

**Pull request closed without merging**
